### ISSUE TITLE
Unable to open Macintosh application

### ISSUE THREAD

**Issue by warthog3** [apprenticeharper/DeDRM_tools#136]
I have tried many different methods to try to make this application to work, but I continue to get the following error message:

http://imgur.com/a/rTNZz

Is there something I may be doing wrong or is there a problem with the most recent build?

**Comment by zaptrem** [comment]
Have you tried using the Calibre plugin? Probably easier to use.

**Comment by warthog3** [comment]
I've had some success with the Calibre plugin, but having trouble with an epub (Adobe Digital Editions). I'm trying everything I can with no luck.

**Comment by zaptrem** [comment]
Have you tried opening Calibre in debug mode, making sure Calibre's library is empty, then trying to import it again and looking at the resulting log for more hints? It would also be helpful to post it here.

**Comment by warthog3** [comment]
Running El Capitan (10.11.6) and most recent version of Calibre (2.68). Have been able to use the plugin on some Amazon ebooks without issue, but can't seem to get this plugin working on an Adobe Digital Editions book. Uninstalled ADE and downgraded to ADE version 2.0.1 just to see if it'd help. I'd be happy if I could get the plugin working, but I'm also perplexed as to why the Mac app doesn't open.

Was also able to run the python script from the Windows folder, but still couldn't get it to remove DRM from this ADE epub.

http://imgur.com/a/khjeD

**Comment by zaptrem** [comment]
Christ, that was a fast response!

**Comment by warthog3** [comment]
I was already typing a follow-up comment. I'll run Calibre in debug mode now.

**Comment by warthog3** [comment]
So here's the debug output. Seems like it's a key issue.

> calibre Debug log
> calibre 2.68  embedded-python: True is64bit: True
> Darwin-15.6.0-x86_64-i386-64bit Darwin ('64bit', '')
> ('Darwin', '15.6.0', 'Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64')
> Python 2.7.11
> OSX: ('10.11.6', ('', '', ''), 'x86_64')
> Successfully initialized third party plugins: DeDRM (6, 5, 1)
> devicePixelRatio: 1.0
> logicalDpi: 72.0 x 72.0
> physicalDpi: 111.000001667 x 110.000001652
> Starting up...
> Started up in 2.64 seconds with 11 books
> DeDRM v6.5.1: Trying to decrypt Being Mortal.epub
> DeDRM v6.5.1: Verifying zip archive integrity
> DeDRM v6.5.1: Being Mortal.epub is a secure Adobe Adept ePub
> DeDRM v6.5.1: Trying Encryption key default_key
> Could not decrypt a7cllK.epub. Wrong key
> DeDRM v6.5.1: Failed to decrypt with key default_key after 0.1 seconds
> DeDRM v6.5.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
> DeDRM v6.5.1: Ultimately failed to decrypt after 0.1 seconds.
> Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
> Running file type plugin DeDRM failed with traceback:
> Traceback (most recent call last):
>   File "site-packages/calibre/customize/ui.py", line 154, in _run_filetype_plugins
>   File "calibre_plugins.dedrm.__init__", line 619, in run
>   File "calibre_plugins.dedrm.__init__", line 390, in ePubDecrypt
> DeDRMError: DeDRM v6.5.1: Ultimately failed to decrypt after 0.1 seconds.
> 2016-09-24 14:40:58.492 calibre-debug[8171:415121] plugin com.getdropbox.dropbox.garcon invalidated
> Added Being Mortal to db in: 0.0
> Added 1 books in 0.9 seconds

**Comment by zaptrem** [comment]
Did you change the key file parameter in the plugin settings to your own key file/s?

**Comment by warthog3** [comment]
I've tried changing the settings for the plugin in Calibre, but I'm not sure where the key would be located for this ebook. I can remove the default_key and replace it, but that's all I've been able to do.

**Comment by warthog3** [comment]
I just tried independently running the python script - adobekey.py - in the Plugin folder. It generated a key which I then pointed the plugin to in the options dialogue. This is the relevant debug output from that unsuccessful try:

> DeDRM v6.5.1: Being Mortal.epub is a secure Adobe Adept ePub
DeDRM v6.5.1: Trying Encryption key adobekey_1
Could not decrypt rFbvlL.epub. Wrong key
DeDRM v6.5.1: Failed to decrypt with key adobekey_1 after 0.1 seconds
DeDRM v6.5.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.5.1: Ultimately failed to decrypt after 0.1 seconds.

**Comment by warthog3** [comment]
Somehow got a new key generated in the plugin options and the DRM was finally removed. The primary issue I opened still remains - can't open the Mac app.

**Comment by zaptrem** [comment]
Once the DRM has been removed, you should be able to use Calibre to convert it to a pdf (if that is what you want to do) and you no longer need any of the tools provided by these fine developers.

**Comment by apprenticeharper** [comment]
I don't have a Mac myself. The Mac application is maintained by someone who prefers to remain anonymous. (I can update it with new versions of scripts.)

As far as I know, any problem opening the Mac application is down to the Mac's security preferences as related to unsigned applications. If it were a general problem, I'd expect to have had more reports.

**Comment by StewGoin** [comment]
Looks like a permissions issue in the latest release.

Assuming you move DeDRM to your /Applications folder, this ought to work:
`chmod +x /Applications/DeDRM.app/Contents/MacOS/droplet`

Then run/open the app.

**Comment by warthog3** [comment]
Thank you very much @StewGoin!!

**Comment by warthog3** [comment]
I think I probably I preemptively 'fixed' this issue. @apprenticeharper Can the person who helps with the mac builds fix this permissions issue?

**Comment by apprenticeharper** [comment]
I'll pass on the message. And I'll see what I can do with a VM - perhaps I can reproduce the problem.

**Comment by apprenticeharper** [comment]
I think this is fixed in v6.5.2

**Comment by warthog3** [comment]
@apprenticeharper Still having the same issue opening the Mac app. Seen here: http://imgur.com/a/rTNZz

The permissions fix that @StewGoin described seems to fix it.

> Looks like a permissions issue in the latest release.
Assuming you move DeDRM to your /Applications folder, this ought to work:
chmod +x /Applications/DeDRM.app/Contents/MacOS/droplet
Then run/open the app.

**Comment by pdurrant** [comment]
I only use the plugin these days, but I'll give the Mac app a go this evening myself. (I don't remember ever being unable to run it, but that was a few OSes ago!)

**Comment by apprenticeharper** [comment]
@warthog3 Thanks for the report. I'll pass it on to my Mac dev* and see what they say.

@pdurrant Any additional  insight on this issue would be helpful


*That sounds a lot more official than the actual situation!

**Comment by pdurrant** [comment]
I'm on Mac OS X 10.11.6. I've just downloaded the DeDRM_6.5.2 release archive, unzipped it, and used the terminal to check the droplet file. The owner of the file is me, and the permissions are rwxr-xr-x

When I try to run the application by double-clicking it I get:

“DeDRM.app” can’t be opened because it is from an unidentified developer.

Your security preferences allow installation of only apps from the Mac App Store and identified developers.


But if I right-click and select "Open" from the pop-up menu I get

“DeDRM.app” is from an unidentified developer. Are you sure you want to open it?

Opening “DeDRM.app” will always allow it to run on this Mac.

And clicking the Open button opens the app.

Hmm... I see I'm being offered MacOS Sierra as a free upgrade. Perhaps that's the difference?

**Comment by apprenticeharper** [comment]
It turns out that 'my' Mac dev is also currently on Mac OS X 10.11

Could those who have seen the no-execution-bit bug please report which version of Mac OS X they are running?

**Comment by warthog3** [comment]
I'm running 10.11.6 - most recent update of El Capitan.
____________________________________________________________
Do This Before Bed Tonight to Burn Belly Flab All Night Long
Flat Belly Protacol
http://thirdpartyoffers.juno.com/TGL3131/58050a715c65ca717faest01vuc

**Comment by pdurrant** [comment]
@warthog: Well, that's odd. I checked using the terminal immediately after unzipping it (using the built-in extractor). If you unzip the archive, does it show up without the execution bit set for you?

**Comment by warthog3** [comment]
> If you unzip the archive, does it show up without the execution bit set for you?

@pdurrant, you figured it out. I've been using a 3rd party unzip utility - Keka. http://www.kekaosx.com/en/

When I unzip it using the built-in extractor, the prompt to open the app from an 'unidentified developer' pops up and I'm able to open it. So it's my unzip utility's fault for this permissions problem. Thanks.

**Comment by apprenticeharper** [comment]
Thanks, both. I'll add something to the FAQs.
